# Generated by Django 2.1.1 on 2018-09-06 20:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.CharField(max_length=20, unique=True)),
                ('time_limit_C', models.IntegerField(default=1000)),
                ('time_limit_other', models.IntegerField(default=2000)),
                ('memory_limit', models.IntegerField(default=65536)),
                ('memory_limit_other', models.IntegerField(default=32768)),
                ('description', models.TextField()),
                ('input_decscription', models.TextField()),
                ('output_decscription', models.TextField()),
                ('sample_input', models.TextField()),
                ('sample_output', models.TextField()),
                ('hint', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('add_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
