# Generated by Django 2.1.1 on 2018-09-07 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='题目添加时间'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='description',
            field=models.TextField(verbose_name='题目描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='hint',
            field=models.TextField(blank=True, verbose_name='题目提示'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='idd',
            field=models.CharField(max_length=20, unique=True, verbose_name='题目编号'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_decscription',
            field=models.TextField(verbose_name='输入描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit',
            field=models.IntegerField(default=65536, verbose_name='内存限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='memory_limit_other',
            field=models.IntegerField(default=32768, verbose_name='其他语言内存限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='output_decscription',
            field=models.TextField(verbose_name='输出描述'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_input',
            field=models.TextField(verbose_name='样例输入'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='sample_output',
            field=models.TextField(verbose_name='样例输出'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='source',
            field=models.CharField(blank=True, max_length=200, verbose_name='题目来源'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit_C',
            field=models.IntegerField(default=1000, verbose_name='时间限制'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='time_limit_other',
            field=models.IntegerField(default=2000, verbose_name='其他语言限制'),
        ),
    ]
