# Generated by Django 2.1.3 on 2018-11-26 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_auto_20181126_1918'),
        ('problems', '0002_auto_20181126_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='id',
            new_name='problem_id',
        ),
        migrations.AddField(
            model_name='problem',
            name='contest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.Contest'),
        ),
    ]
