# Generated by Django 2.1.3 on 2018-12-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_contest'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='is_contested',
            field=models.BooleanField(default=False, verbose_name='正在比赛'),
        ),
        migrations.AddField(
            model_name='problem',
            name='is_visual',
            field=models.BooleanField(default=True, verbose_name='可视'),
        ),
    ]
