# Generated by Django 2.1.1 on 2018-09-07 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='用户注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='邮箱地址'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='personal_status',
            field=models.CharField(blank=True, max_length=140, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='problem_solved',
            field=models.IntegerField(default=0, verbose_name='通过题目'),
        ),
        migrations.AlterField(
            model_name='user',
            name='problem_submit',
            field=models.IntegerField(default=0, verbose_name='累计提交'),
        ),
    ]
