# Generated by Django 2.1.1 on 2018-09-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_status',
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name='user',
            name='problem_solved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='problem_submit',
            field=models.IntegerField(default=0),
        ),
    ]
