# Generated by Django 2.1.1 on 2018-11-26 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='比赛编号')),
                ('title', models.CharField(blank=True, max_length=1000, verbose_name='比赛标题')),
                ('description', models.TextField(blank=True, verbose_name='比赛描述')),
                ('hint', models.TextField(blank=True, verbose_name='题目提示')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='比赛开始时间')),
                ('accepted', models.IntegerField(default=0, verbose_name='报名人数')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='出题人来源')),
            ],
        ),
    ]
