# Generated by Django 2.1.1 on 2018-11-26 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='hint',
        ),
    ]
