# Generated by Django 2.1.1 on 2018-11-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0002_remove_contest_hint'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest',
            old_name='accepted',
            new_name='people',
        ),
    ]
