# Generated by Django 2.1.3 on 2018-11-29 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_remove_problem_contest'),
        ('contest', '0003_auto_20181126_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest_problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_num', models.IntegerField()),
                ('submit_num', models.IntegerField()),
                ('contest_problem_id', models.CharField(max_length=5)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='id',
            new_name='contest_id',
        ),
        migrations.AddField(
            model_name='contest_problem',
            name='contest_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contest.Contest'),
        ),
        migrations.AddField(
            model_name='contest_problem',
            name='problem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='problems.Problem'),
        ),
    ]
