# Generated by Django 2.1.3 on 2018-11-29 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_auto_20181129_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contest_problem',
            old_name='contest_id',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='contest_problem',
            old_name='problem_id',
            new_name='problem',
        ),
        migrations.RemoveField(
            model_name='contest_problem',
            name='id',
        ),
        migrations.AlterField(
            model_name='contest_problem',
            name='contest_problem_id',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
