# Generated by Django 2.1.3 on 2018-11-29 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_auto_20181129_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest_problem',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contest', to='contest.Contest'),
        ),
        migrations.AlterField(
            model_name='contest_problem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='problem', to='problems.Problem'),
        ),
    ]
