# Generated by Django 2.1.3 on 2018-11-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0006_auto_20181129_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest_problem',
            name='contest',
        ),
        migrations.RemoveField(
            model_name='contest_problem',
            name='problem',
        ),
        migrations.AddField(
            model_name='contest_problem',
            name='contest_id',
            field=models.CharField(default='A001', max_length=20),
        ),
        migrations.AddField(
            model_name='contest_problem',
            name='problem_id',
            field=models.CharField(default='1000', max_length=20),
        ),
    ]
