# Generated by Django 2.1.3 on 2018-12-02 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_auto_20181129_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='add_time',
        ),
        migrations.AddField(
            model_name='contest',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2018, 12, 2, 15, 2, 57, 648360), verbose_name='结束时间'),
        ),
        migrations.AddField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 10, 2, 57, 648330), verbose_name='比赛开始时间'),
        ),
    ]
