# Generated by Django 2.1.3 on 2018-12-02 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0012_auto_20181202_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest_problem',
            name='contest_problem_id',
            field=models.CharField(default='NULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='contest',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2018, 12, 2, 16, 41, 17, 401052), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 11, 41, 17, 401023), verbose_name='比赛开始时间'),
        ),
    ]
