# Generated by Django 2.1.3 on 2018-12-02 12:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_auto_20181202_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='endtime',
            field=models.DateField(default=datetime.datetime(2018, 12, 2, 17, 23, 30, 470042), verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 2, 12, 23, 30, 470006), verbose_name='比赛开始时间'),
        ),
    ]
